version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_SOCKET_URL: http://localhost:4000
    ports:
      - '3000:80'
    depends_on:
      - socket-server

  socket-server:
    build:
      context: .
      dockerfile: Dockerfile.socket
    ports:
      - '4000:4000'